language: python
python:
  - "3.7.4"

before_install:
  - "pip install -U pip"
  - "export PYTHONPATH=$PYTHONPATH:$(pwd)"
  
install:
  - pip install pipenv
  - pipenv install --dev

script:
  - pytest